### ISSUE TITLE
Improve behind tracker notifications

### ISSUE THREAD

**Issue by zielu** [zielu/GitToolBox#76]
- [x] when switching branches show only repos that were in fact switched
- [x] when fetched show only repos that had changed commits 
- [x] display number of new commit after fetch

**Comment by zielu** [comment]
Need to set longer notification schedule time - 20 sec ? - to wait for all repo updates happening in the background.
